MvcKutuphane/Controllers/DuyuruController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class DuyuruController : Controller
    {
        // GET: Duyuru
        DBKUTUPHANEEntities db=new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler=db.TBLDUYURULAR.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniDuyuru()
        { 
            return View();
        }
        [HttpPost]
        public ActionResult YeniDuyuru(TBLDUYURULAR d)
        {
            db.TBLDUYURULAR.Add(d);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DuyuruSil(int  id) 
        { 
           var duyuru=db.TBLDUYURULAR.Find(id);
            db.TBLDUYURULAR.Remove(duyuru);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DuyuruDetay(TBLDUYURULAR d)
        {
            var duyuru = db.TBLDUYURULAR.Find(d.Id);
            return View("DuyuruDetay", duyuru);
        }

        public ActionResult DuyuruGuncelle(TBLDUYURULAR t)
        {
            var duyuru = db.TBLDUYURULAR.Find(t.Id);
            duyuru.KATEGORI=t.KATEGORI;
            duyuru.ICERIK=t.ICERIK;
            duyuru.TARIH=t.TARIH;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcKutuphane/Views/Duyuru/DuyuruDetay.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURULAR
@{
    ViewBag.Title = "DuyuruDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("DuyuruGuncelle", "Duyuru", FormMethod.Post))
{
    <div style=" margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.Id)
        @Html.TextBoxFor(k => k.Id, new { @class = "form-control" })
        <br />
        <label>Duyuru Kategori</label>
        @Html.TextBoxFor(k => k.KATEGORI, new { @class = "form-control" })
        <br />
        <label>Duyuru İçerik</label>
        @Html.TextAreaFor(k => k.ICERIK, new { @class = "form-control" })
        <br />
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(k => k.TARIH, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Duyuru/Index.cshtml
@using MvcKutuphane.Models.Entity;
@model List<TBLDUYURULAR>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
    string renk = "";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<table class="table table-bordered">
    <tr>
        <th>Duyuru No</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>İçerik</th>
    </tr>
    @foreach (var item in Model)
    {
        if (item.KATEGORI == "Diğer")
        {
            renk = "bg-info text-white";
        }
        if (item.KATEGORI == "Yeni Kitap")
        {
            renk = "bg-warning text-white";
        }
        if (item.KATEGORI == "İletişim")
        {
            renk = "bg-success text-white";
        }
        if (item.KATEGORI == "Kitapları Geciktirmeyin")
        {
            renk = "bg-danger text-white";
        }
        <tr class="@renk">
            <td>@item.Id</td>
            <td>@item.KATEGORI</td>
            <td>@Convert.ToDateTime(item.TARIH).ToString("dd/MM/yyyy")</td>
            <td><a href="/Duyuru/DuyuruSil/@item.Id" class="btn btn-danger">Sil</a></td>
            <td><a href="/Duyuru/DuyuruDetay/@item.Id" class="btn btn-default" style="background-color:skyblue">Detaylar</a></td>
        </tr>
    }
</table>
<a href="/Duyuru/YeniDuyuru/" class="btn btn-primary">Yeni Duyuru Ekle</a>

MvcKutuphane/Views/Duyuru/YeniDuyuru.cshtml
@model MvcKutuphane.Models.Entity.TBLDUYURULAR
@{
    ViewBag.Title = "YeniDuyuru";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label>Duyuru Kategorisi</label>
        @Html.TextBoxFor(x => x.KATEGORI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Duyuru İçerik</label>
        @Html.TextBoxFor(x => x.ICERIK, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Duyuru Tarih</label>
        @Html.TextBoxFor(x => x.TARIH, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Duyuru Ekle</button>
    </div>
</form>