MvcKutuphane/Controllers/AyarlarController.cs
using MvcKutuphane.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcKutuphane.Controllers
{
    public class AyarlarController : Controller
    {
        // GET: Ayarlar
        DBKUTUPHANEEntities db=new DBKUTUPHANEEntities();   
        public ActionResult Index()
        {
            var kullaniciler=db.TBLADMIN.ToList();
            return View(kullaniciler);
        }

        public ActionResult Index2()
        {
            var kullaniciler = db.TBLADMIN.ToList();
            return View(kullaniciler);
        }
        [HttpGet]
        public ActionResult YeniAdmin() 
        { 
        return View();
        }
        [HttpPost]
        public ActionResult YeniAdmin(TBLADMIN t)
        {
            db.TBLADMIN.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
        public ActionResult AdminSil(int id)
        {
            var admin = db.TBLADMIN.Find(id);
            db.TBLADMIN.Remove(admin);
            db.SaveChanges();
            return RedirectToAction("Index2");
        }

        [HttpGet]
        public ActionResult AdminGuncelle(int id) 
        {
            var admin = db.TBLADMIN.Find(id);
            return View("AdminGüncelle", admin);
        }
        [HttpPost]
        public ActionResult AdminGuncelle(TBLADMIN p)
        {
            var admin = db.TBLADMIN.Find(p.Id);
            admin.KULLANICI = p.KULLANICI;
            admin.SIFRE=p.SIFRE;
            admin.YETKI= p.YETKI;
            db.SaveChanges();
            return RedirectToAction("Index2");
        }
    }
}

MvcKutuphane/Views/Ayarlar/AdminGüncelle.cshtml
@model MvcKutuphane.Models.Entity.TBLADMIN
@{
    ViewBag.Title = "AdminGüncelle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("AdminGuncelle", "Ayarlar", FormMethod.Post))
{
    <div style=" margin-bottom:15px"></div>
    <div class="form-group">
        @Html.LabelFor(k => k.Id)
        @Html.TextBoxFor(k => k.Id, new { @class = "form-control" })
        <br />
        <label>Kullanıcı ADI</label>
        @Html.TextBoxFor(k => k.KULLANICI, new { @class = "form-control" })
        <br />
        <label>Şifre</label>
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })
        <br />
        <label>Ytki</label>
        @Html.TextBoxFor(k => k.YETKI, new { @class = "form-control" })
        <br />
    </div>
    <br />
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}

MvcKutuphane/Views/Ayarlar/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Projects</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
            <section class="content">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Projects</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 1%">
                                        #
                                    </th>
                                    <th style="width: 20%">
                                        Kullanıcı Adı
                                    </th>
                                    <th style="width: 10%">
                                        Avatar
                                    </th>
                                    <th style="width: 8%" class="text-center">
                                        Yetki
                                    </th>
                                    <th style="width: 20%">
                                        İşlemler
                                    </th>                                   
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        #
                                    </td>
                                    <td>
                                        <a>
                                            AdminLTE v3
                                        </a>
                                    </td>
                                    <td>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">
                                                <img alt="Avatar" class="table-avatar" src="~/AdminLTE-3.0.4/dist/img/avatar.png">
                                            </li>                                         
                                        </ul>
                                    </td>                                   
                                    <td class="project-state">
                                        <span class="badge badge-success">Success</span>
                                    </td>
                                    <td class="project-actions text-right">
                                        <a class="btn btn-info btn-sm" href="#">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Düzenle
                                        </a>
                                        <a class="btn btn-danger btn-sm" href="#">
                                            <i class="fas fa-trash">
                                            </i>
                                            Sil
                                        </a>
                                    </td>
                                </tr>
                                
                            </tbody>
                        </table>
                    </div>
                </div>
            </section>
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
</body>
</html>

MvcKutuphane/Views/Ayarlar/Index2.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLADMIN>
@{
    ViewBag.Title = "Index2";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">

<br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Kulanıcı</th>
        <th>Yetki</th>
        <th>Sil</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.KULLANICI</td>
            <td>@item.YETKI</td>
            <td>
                <a class="btn btn-info btn-sm" href="/Ayarlar/AdminGuncelle/@item.Id">
                    <i class="fas fa-pencil-alt">
                    </i>
                    Düzenle
                </a>
            </td>
            <td>
                <a class="btn btn-danger btn-sm" href="/Ayarlar/AdminSil/@item.Id">
                    <i class="fas fa-trash">
                    </i>
                    Sil
                </a>
            </td>
        </tr>
    }
</table>
<br />

<button class="btn btn-primary" data-toggle="modal" data-target="#Modal1">Yeni Admin Ekle</button>
<div class="modal" id="Modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title">Admin Ekleme Paneli</h2>
            </div>
            <form method="post" action="/Ayarlar/YeniAdmin/">
                <div class="modal-body">
                    <label>Kullanıcı Adı</label>
                    <input type="text" name="KULLANICI" class="form-control" />
                    <br />
                    <label>Şifre</label>
                    <input type="text" name="SIFRE" class="form-control" />
                    <br />
                    <label>Yetki</label>
                    <input type="text" name="YETKI" class="form-control" />
                    <br />
                    <button class="btn btn-info">Kaydet</button>
                </div>
            </form>
        </div>
    </div>
</div>